<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
        "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="" lang="">
<head>
  <title>Test Results Report - ApiTest</title>
  <meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
  <meta name="description" content="TestNG unit test results." />
  <link href="reportng.css" rel="stylesheet" type="text/css" />
    <script type="text/javascript" src="reportng.js"></script>
</head>
<body>
<h1>ApiTest</h1>
<p>
  Test duration: 10.157s
</p>



  <table class="resultsTable">
    <tr><th colspan="3" class="header failed">Failed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">automationFramework.TestCases.ApiCustomerPost</td>
      </tr>
            
<tr>
  <td class="method">
                  apiErrorAddressId
      </td>
  <td class="duration">
    1.341s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-0', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-0">
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorAddressId(ApiCustomerPost.java:198)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankAddress
      </td>
  <td class="duration">
    0.078s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-1', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [If address is provided, address1 is required.] but found [Field is blank.]</b></a><br />
    <div class="stackTrace" id="exception-1">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankAddress(ApiCustomerPost.java:210)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankCity
      </td>
  <td class="duration">
    0.032s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-2', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [If address is provided, city is required.] but found [Field is blank.]</b></a><br />
    <div class="stackTrace" id="exception-2">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankCity(ApiCustomerPost.java:248)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankCountry
      </td>
  <td class="duration">
    0.046s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-3', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [If address is provided, country is required.] but found [Field is blank.]</b></a><br />
    <div class="stackTrace" id="exception-3">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankCountry(ApiCustomerPost.java:272)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPassword
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-4', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Field is blank.] but found [null]</b></a><br />
    <div class="stackTrace" id="exception-4">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPassword(ApiCustomerPost.java:647)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPersonalId
      </td>
  <td class="duration">
    0.031s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-5', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [If personal identifier info is provided, personal identifier is required.] but found [Field is blank.]</b></a><br />
    <div class="stackTrace" id="exception-5">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPersonalId(ApiCustomerPost.java:534)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPersonalIdType
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-6', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [If personal identifier info is provided, personal identifier type is required.] but found [Field is blank.]</b></a><br />
    <div class="stackTrace" id="exception-6">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPersonalIdType(ApiCustomerPost.java:558)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneNumber
      </td>
  <td class="duration">
    0.046s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-7', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [If phone is provided, phone number is required.] but found [Field is blank.]</b></a><br />
    <div class="stackTrace" id="exception-7">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneNumber(ApiCustomerPost.java:342)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneNumber2
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-8', 'block')" title="Click to expand/collapse"><b>java.lang.IndexOutOfBoundsException: Index: 1, Size: 1</b></a><br />
    <div class="stackTrace" id="exception-8">
              java.util.ArrayList.rangeCheck(Unknown Source)<br />
              java.util.ArrayList.get(Unknown Source)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneNumber2(ApiCustomerPost.java:387)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneNumber3
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-9', 'block')" title="Click to expand/collapse"><b>java.lang.IndexOutOfBoundsException: Index: 2, Size: 1</b></a><br />
    <div class="stackTrace" id="exception-9">
              java.util.ArrayList.rangeCheck(Unknown Source)<br />
              java.util.ArrayList.get(Unknown Source)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneNumber3(ApiCustomerPost.java:435)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneType
      </td>
  <td class="duration">
    0.031s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-10', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [If phone1 is provided, phone type is required.] but found [Field is blank.]</b></a><br />
    <div class="stackTrace" id="exception-10">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneType(ApiCustomerPost.java:366)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneType2
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-11', 'block')" title="Click to expand/collapse"><b>java.lang.IndexOutOfBoundsException: Index: 1, Size: 1</b></a><br />
    <div class="stackTrace" id="exception-11">
              java.util.ArrayList.rangeCheck(Unknown Source)<br />
              java.util.ArrayList.get(Unknown Source)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneType2(ApiCustomerPost.java:411)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPhoneType3
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-12', 'block')" title="Click to expand/collapse"><b>java.lang.IndexOutOfBoundsException: Index: 2, Size: 1</b></a><br />
    <div class="stackTrace" id="exception-12">
              java.util.ArrayList.rangeCheck(Unknown Source)<br />
              java.util.ArrayList.get(Unknown Source)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPhoneType3(ApiCustomerPost.java:459)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankPostalCode
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-13', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [If address is provided, postal code is required.] but found [Field is blank.]</b></a><br />
    <div class="stackTrace" id="exception-13">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankPostalCode(ApiCustomerPost.java:318)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankState
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-14', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [If address is provided, state is required.] but found [Field is blank.]</b></a><br />
    <div class="stackTrace" id="exception-14">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorBlankState(ApiCustomerPost.java:295)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainConsecutiveCharacterPin
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-15', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-15">
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorContainConsecutiveCharacterPin(ApiCustomerPost.java:781)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainContigousCharacterPin
      </td>
  <td class="duration">
    0.046s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-16', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-16">
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorContainContigousCharacterPin(ApiCustomerPost.java:793)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainDictionaryPassword
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-17', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-17">
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorContainDictionaryPassword(ApiCustomerPost.java:756)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainDigitsPassword
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-18', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-18">
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorContainDigitsPassword(ApiCustomerPost.java:708)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainLettersPassword
      </td>
  <td class="duration">
    0.032s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-19', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [errors.password.must.contain.atleast.chars] but found [errors.password.cannot.contain.contiguous.chars]</b></a><br />
    <div class="stackTrace" id="exception-19">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorContainLettersPassword(ApiCustomerPost.java:732)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainSameCharacterPassword
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-20', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [errors.password.cannot.contain.same.char.consecutively] but found [errors.password.cannot.contain.contiguous.chars]</b></a><br />
    <div class="stackTrace" id="exception-20">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorContainSameCharacterPassword(ApiCustomerPost.java:672)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainSpecialCharactersPassword
      </td>
  <td class="duration">
    0.046s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-21', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-21">
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorContainSpecialCharactersPassword(ApiCustomerPost.java:744)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainUsernamePassword
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-22', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Password can not contain username in it.] but found [{errors.password.cannot.contain.username}]</b></a><br />
    <div class="stackTrace" id="exception-22">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorContainUsernamePassword(ApiCustomerPost.java:659)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorDuplicateUserName
      </td>
  <td class="duration">
    0.109s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-23', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Value already exists] but found [null]</b></a><br />
    <div class="stackTrace" id="exception-23">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorDuplicateUserName(ApiCustomerPost.java:636)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidContactType
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-24', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Invalid contact type.] but found [Invalid value.]</b></a><br />
    <div class="stackTrace" id="exception-24">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidContactType(ApiCustomerPost.java:93)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidCountry
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-25', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Invalid country.] but found [Invalid value.]</b></a><br />
    <div class="stackTrace" id="exception-25">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidCountry(ApiCustomerPost.java:284)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidCustomerType
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-26', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Invalid customer type.] but found [Invalid value.]</b></a><br />
    <div class="stackTrace" id="exception-26">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidCustomerType(ApiCustomerPost.java:72)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPersonalIdType
      </td>
  <td class="duration">
    0.015s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-27', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Invalid personal identifier type.] but found [Invalid value.]</b></a><br />
    <div class="stackTrace" id="exception-27">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPersonalIdType(ApiCustomerPost.java:570)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneNumber
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-28', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Invalid phone number.] but found [Invalid format dictated by country.]</b></a><br />
    <div class="stackTrace" id="exception-28">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneNumber(ApiCustomerPost.java:354)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneNumber2
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-29', 'block')" title="Click to expand/collapse"><b>java.lang.IndexOutOfBoundsException: Index: 1, Size: 1</b></a><br />
    <div class="stackTrace" id="exception-29">
              java.util.ArrayList.rangeCheck(Unknown Source)<br />
              java.util.ArrayList.get(Unknown Source)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneNumber2(ApiCustomerPost.java:399)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneNumber3
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-30', 'block')" title="Click to expand/collapse"><b>java.lang.IndexOutOfBoundsException: Index: 2, Size: 1</b></a><br />
    <div class="stackTrace" id="exception-30">
              java.util.ArrayList.rangeCheck(Unknown Source)<br />
              java.util.ArrayList.get(Unknown Source)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneNumber3(ApiCustomerPost.java:447)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneType
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-31', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Invalid phone type.] but found [Invalid value.]</b></a><br />
    <div class="stackTrace" id="exception-31">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneType(ApiCustomerPost.java:378)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneType2
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-32', 'block')" title="Click to expand/collapse"><b>java.lang.IndexOutOfBoundsException: Index: 1, Size: 1</b></a><br />
    <div class="stackTrace" id="exception-32">
              java.util.ArrayList.rangeCheck(Unknown Source)<br />
              java.util.ArrayList.get(Unknown Source)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneType2(ApiCustomerPost.java:423)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPhoneType3
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-33', 'block')" title="Click to expand/collapse"><b>java.lang.IndexOutOfBoundsException: Index: 2, Size: 1</b></a><br />
    <div class="stackTrace" id="exception-33">
              java.util.ArrayList.rangeCheck(Unknown Source)<br />
              java.util.ArrayList.get(Unknown Source)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidPhoneType3(ApiCustomerPost.java:471)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidState
      </td>
  <td class="duration">
    0.062s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-34', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Invalid state.] but found [Invalid value.]</b></a><br />
    <div class="stackTrace" id="exception-34">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidState(ApiCustomerPost.java:307)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidSuffixId
      </td>
  <td class="duration">
    0.046s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-35', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-35">
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidSuffixId(ApiCustomerPost.java:186)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidUserName
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-36', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [errors.general.email.invalid.format.] but found [errors.general.email.invalid.format]</b></a><br />
    <div class="stackTrace" id="exception-36">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorInvalidUserName(ApiCustomerPost.java:617)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthPassword
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-37', 'block')" title="Click to expand/collapse"><b>com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field &quot;params&quot; (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , &quot;uid&quot;, &quot;fieldName&quot;, &quot;errorKey&quot;, &quot;result&quot;, &quot;errorMessage&quot;])<br/>
 at [Source: java.io.StringReader@7c28c1; line: 1, column: 207] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse[&quot;hdr&quot;]-&gt;automationFramework.TestCases.RestResponseHeader[&quot;params&quot;])</b></a><br />
    <div class="stackTrace" id="exception-37">
              com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)<br />
              com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)<br />
              com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)<br />
              com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)<br />
              com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)<br />
              com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)<br />
              com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2048)<br />
              com.fasterxml.jackson.databind.ObjectMapper$readValue$2.call(Unknown Source)<br />
              com.jayway.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:43)<br />
              com.jayway.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:60)<br />
              com.jayway.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:202)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping$parseWithJackson2$1.callStatic(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:55)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)<br />
              com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:216)<br />
              com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:159)<br />
              automationFramework.TestCases.ApiCustomerPost.sendAPIRequest(ApiCustomerPost.java:972)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorMaxLengthPassword(ApiCustomerPost.java:695)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthUserName
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-38', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [errors.general.value.toolong] but found [errors.general.email.invalid.format]</b></a><br />
    <div class="stackTrace" id="exception-38">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorMaxLengthUserName(ApiCustomerPost.java:593)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaximumLengthEmail
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-39', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-39">
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorMaximumLengthEmail(ApiCustomerPost.java:498)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMinLengthPassword
      </td>
  <td class="duration">
    0.031s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-40', 'block')" title="Click to expand/collapse"><b>com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field &quot;params&quot; (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , &quot;uid&quot;, &quot;fieldName&quot;, &quot;errorKey&quot;, &quot;result&quot;, &quot;errorMessage&quot;])<br/>
 at [Source: java.io.StringReader@6bcbf05b; line: 1, column: 185] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse[&quot;hdr&quot;]-&gt;automationFramework.TestCases.RestResponseHeader[&quot;params&quot;])</b></a><br />
    <div class="stackTrace" id="exception-40">
              com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)<br />
              com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)<br />
              com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)<br />
              com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)<br />
              com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)<br />
              com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)<br />
              com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2048)<br />
              com.fasterxml.jackson.databind.ObjectMapper$readValue$2.call(Unknown Source)<br />
              com.jayway.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:43)<br />
              com.jayway.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:60)<br />
              com.jayway.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:202)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping$parseWithJackson2$1.callStatic(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:55)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)<br />
              com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:216)<br />
              com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:159)<br />
              automationFramework.TestCases.ApiCustomerPost.sendAPIRequest(ApiCustomerPost.java:972)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorMinLengthPassword(ApiCustomerPost.java:683)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMixCasesPassword
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-41', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-41">
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:993)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorMixCasesPassword(ApiCustomerPost.java:720)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSecurityAnswerBlank
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-42', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-42">
              automationFramework.TestCases.ApiCustomerPost.apiErrorSecurityAnswerBlank(ApiCustomerPost.java:862)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSecurityAnswerMaxLength
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-43', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-43">
              automationFramework.TestCases.ApiCustomerPost.apiErrorSecurityAnswerMaxLength(ApiCustomerPost.java:874)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSecurityQuestionBlank
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-44', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-44">
              automationFramework.TestCases.ApiCustomerPost.apiErrorSecurityQuestionBlank(ApiCustomerPost.java:838)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSecurityQuestionInvalid
      </td>
  <td class="duration">
    0.000s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-45', 'block')" title="Click to expand/collapse"><b>java.lang.NullPointerException</b></a><br />
    <div class="stackTrace" id="exception-45">
              automationFramework.TestCases.ApiCustomerPost.apiErrorSecurityQuestionInvalid(ApiCustomerPost.java:850)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSpecialCharactersEmail
      </td>
  <td class="duration">
    0.031s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-46', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Cannot start with special characters: &quot;.&quot; ,&quot;@&quot; or &quot;www.&quot;] but found [Email cannot start with special characters.]</b></a><br />
    <div class="stackTrace" id="exception-46">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorSpecialCharactersEmail(ApiCustomerPost.java:510)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorSpecialCharactersUserName
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-47', 'block')" title="Click to expand/collapse"><b>java.lang.AssertionError: expected [Cannot start with special characters: &quot;.&quot; ,&quot;@&quot; or &quot;www.&quot;] but found [Email cannot start with special characters.]</b></a><br />
    <div class="stackTrace" id="exception-47">
              org.testng.Assert.fail(Assert.java:94)<br />
              org.testng.Assert.failNotEquals(Assert.java:494)<br />
              org.testng.Assert.assertEquals(Assert.java:123)<br />
              org.testng.Assert.assertEquals(Assert.java:176)<br />
              org.testng.Assert.assertEquals(Assert.java:186)<br />
              automationFramework.TestCases.ApiCustomerPost.checkError(ApiCustomerPost.java:995)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorSpecialCharactersUserName(ApiCustomerPost.java:605)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorTooLongPin
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-48', 'block')" title="Click to expand/collapse"><b>com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field &quot;params&quot; (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , &quot;uid&quot;, &quot;fieldName&quot;, &quot;errorKey&quot;, &quot;result&quot;, &quot;errorMessage&quot;])<br/>
 at [Source: java.io.StringReader@5ca1f591; line: 1, column: 180] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse[&quot;hdr&quot;]-&gt;automationFramework.TestCases.RestResponseHeader[&quot;params&quot;])</b></a><br />
    <div class="stackTrace" id="exception-48">
              com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)<br />
              com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)<br />
              com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)<br />
              com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)<br />
              com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)<br />
              com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)<br />
              com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2048)<br />
              com.fasterxml.jackson.databind.ObjectMapper$readValue$2.call(Unknown Source)<br />
              com.jayway.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:43)<br />
              com.jayway.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:60)<br />
              com.jayway.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:202)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping$parseWithJackson2$1.callStatic(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:55)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)<br />
              com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:216)<br />
              com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:159)<br />
              automationFramework.TestCases.ApiCustomerPost.sendAPIRequest(ApiCustomerPost.java:972)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorTooLongPin(ApiCustomerPost.java:816)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorTooSmallPin
      </td>
  <td class="duration">
    0.015s
  </td>
  <td class="result">
        
    
        

        <a href="javascript:toggleElement('exception-49', 'block')" title="Click to expand/collapse"><b>com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field &quot;params&quot; (class automationFramework.TestCases.RestResponseHeader), not marked as ignorable (5 known properties: , &quot;uid&quot;, &quot;fieldName&quot;, &quot;errorKey&quot;, &quot;result&quot;, &quot;errorMessage&quot;])<br/>
 at [Source: java.io.StringReader@777c350f; line: 1, column: 180] (through reference chain: automationFramework.TestCases.WSCreateNewCustomerResponse[&quot;hdr&quot;]-&gt;automationFramework.TestCases.RestResponseHeader[&quot;params&quot;])</b></a><br />
    <div class="stackTrace" id="exception-49">
              com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:79)<br />
              com.fasterxml.jackson.databind.DeserializationContext.reportUnknownProperty(DeserializationContext.java:555)<br />
              com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:708)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1160)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:315)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)<br />
              com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)<br />
              com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)<br />
              com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)<br />
              com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)<br />
              com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2048)<br />
              com.fasterxml.jackson.databind.ObjectMapper$readValue$2.call(Unknown Source)<br />
              com.jayway.restassured.internal.path.json.mapping.JsonPathJackson2ObjectDeserializer.deserialize(JsonPathJackson2ObjectDeserializer.groovy:43)<br />
              com.jayway.restassured.path.json.mapping.JsonPathObjectDeserializer$deserialize.call(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.Jackson2Mapper.deserialize(Jackson2Mapper.groovy:60)<br />
              com.jayway.restassured.mapper.ObjectMapper$deserialize$0.call(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping.parseWithJackson2(ObjectMapping.groovy:202)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping$parseWithJackson2$1.callStatic(Unknown Source)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping.deserialize(ObjectMapping.groovy:55)<br />
              com.jayway.restassured.internal.mapping.ObjectMapping$deserialize$0.call(Unknown Source)<br />
              com.jayway.restassured.internal.RestAssuredResponseOptionsGroovyImpl.as(RestAssuredResponseOptionsGroovyImpl.groovy:216)<br />
              com.jayway.restassured.internal.RestAssuredResponseOptionsImpl.as(RestAssuredResponseOptionsImpl.java:159)<br />
              automationFramework.TestCases.ApiCustomerPost.sendAPIRequest(ApiCustomerPost.java:972)<br />
              automationFramework.TestCases.ApiCustomerPost.apiErrorTooSmallPin(ApiCustomerPost.java:804)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br />
              sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)<br />
              sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)<br />
              java.lang.reflect.Method.invoke(Unknown Source)<br />
              org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)<br />
              org.testng.internal.Invoker.invokeMethod(Invoker.java:714)<br />
              org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)<br />
              org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)<br />
              org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br />
              org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br />
              org.testng.TestRunner.privateRun(TestRunner.java:767)<br />
              org.testng.TestRunner.run(TestRunner.java:617)<br />
              org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br />
              org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br />
              org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br />
              org.testng.SuiteRunner.run(SuiteRunner.java:240)<br />
              org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)<br />
              org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)<br />
              org.testng.TestNG.runSuitesSequentially(TestNG.java:1198)<br />
              org.testng.TestNG.runSuitesLocally(TestNG.java:1123)<br />
              org.testng.TestNG.run(TestNG.java:1031)<br />
              org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)<br />
              org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)<br />
              org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)<br />
                </div>
      </td>
</tr>
      </table>


  <table class="resultsTable">
    <tr><th colspan="3" class="header passed">Passed Tests</th></tr>
          <tr>
        <td colspan="3" class="group">automationFramework.TestCases.ApiCustomerPost</td>
      </tr>
            
<tr>
  <td class="method">
                  apiErrorBlankContact
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankContactFirstName
      </td>
  <td class="duration">
    0.031s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankContactLastName
      </td>
  <td class="duration">
    0.032s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankContactName
      </td>
  <td class="duration">
    0.031s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankContactType
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankCustomerType
      </td>
  <td class="duration">
    0.062s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankEmail
      </td>
  <td class="duration">
    0.015s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorBlankUserName
      </td>
  <td class="duration">
    0.015s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorContainUsernamePin
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidFormatEmail
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorInvalidPostalCode
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthAddress
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthAddress2
      </td>
  <td class="duration">
    0.015s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthCity
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthContactFirstName
      </td>
  <td class="duration">
    0.063s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthContactLastName
      </td>
  <td class="duration">
    0.031s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthContactMiddleName
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorMaxLengthPersonalId
      </td>
  <td class="duration">
    0.016s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiErrorNonNumericPin
      </td>
  <td class="duration">
    0.047s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
<tr>
  <td class="method">
                  apiPostSuccess
      </td>
  <td class="duration">
    0.063s
  </td>
  <td class="result">
        
    
        

      </td>
</tr>
      </table>
  
</body>
</html>
